module.exports = [
  'accumulate/README.zh.html',
  'acronym/README.zh.html',
  'all-your-base/README.zh.html',
  'allergies/README.zh.html',
  'anagram/README.zh.html',
  'armstrong-numbers/README.zh.html',
  'atbash-cipher/README.zh.html',
  'beer-song/README.zh.html',
  'binary-search/README.zh.html',
  'bob/README.zh.html',
  'gigasecond/README.zh.html',
  'hello-world/README.zh.html',
  'book-store/README.zh.html',
  'bowling/README.zh.html',
  'bracket-push/README.zh.html',
  'circular-buffer/README.zh.html',
  'clock/README.zh.html',
  'collatz-conjecture/README.zh.html',
  'crypto-square/README.zh.html',
  'custom-set/README.zh.html',
  'difference-of-squares/README.zh.html',
  'diamond/README.zh.html',
  'diffie-hellman/README.zh.html',
  'dominoes/README.zh.html',
  'grep/README.zh.html',
  'etl/README.zh.html',
  'forth/README.zh.html',
  'grade-school/README.zh.html',
  'grains/README.zh.html',
  'hamming/README.zh.html',
  'hexadecimal/README.zh.html',
  'isbn-verifier/README.zh.html',
  'isogram/README.zh.html',
  'largest-series-product/README.zh.html',
  'leap/README.zh.html',
  'luhn-from/README.zh.html',
  'luhn-trait/README.zh.html',
  'luhn/README.zh.html',
  'minesweeper/README.zh.html',
  'macros/README.zh.html',
  'nth-prime/README.zh.html',
  'nucleotide-codons/README.zh.html',
  'ocr-numbers/README.zh.html',
  'palindrome-products/README.zh.html',
  'nucleotide-count/README.zh.html',
  'pangram/README.zh.html',
  'pascals-triangle/README.zh.html',
  'phone-number/README.zh.html',
  'pig-latin/README.zh.html',
  'prime-factors/README.zh.html',
  'protein-translation/README.zh.html',
  'proverb/README.zh.html',
  'pythagorean-triplet/README.zh.html',
  'queen-attack/README.zh.html',
  'raindrops/README.zh.html',
  'rectangles/README.zh.html',
  'rna-transcription/README.zh.html',
  'robot-name/README.zh.html',
  'robot-simulator/README.zh.html',
  'roman-numerals/README.zh.html',
  'rail-fence-cipher/README.zh.html',
  'parallel-letter-frequency/README.zh.html',
  'perfect-numbers/README.zh.html',
  'react/README.zh.html',
  'reverse-string/README.zh.html',
  'rotational-cipher/README.zh.html',
  'run-length-encoding/README.zh.html',
  'saddle-points/README.zh.html',
  'say/README.zh.html',
  'scrabble-score/README.zh.html',
  'series/README.zh.html',
  'sieve/README.zh.html',
  'simple-cipher/README.zh.html',
  'simple-linked-list/README.zh.html',
  'space-age/README.zh.html',
  'spiral-matrix/README.zh.html',
  'sublist/README.zh.html',
  'sum-of-multiples/README.zh.html',
  'tournament/README.zh.html',
  'triangle/README.zh.html',
  'two-bucket/README.zh.html',
  'two-fer/README.zh.html',
  'variable-length-quantity/README.zh.html',
  'word-count/README.zh.html',
  'wordy/README.zh.html'
];

// rust-游乐场没有此库的crate
// 'alphametics/README.zh.html',
// 'dot-dsl/README.zh.html',  
// 'decimal/README.zh.html',
// 'paasio/README.zh.html',
// 'poker/README.zh.html'
// 'scale-generator/README.zh.html',